FROM microsoft/aspnetcore-build:2.0
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

WORKDIR /src
COPY ["SimpleInventory.sln", "./"]
COPY ["SimpleInventory/SimpleInventory.csproj", "SimpleInventory/"]

RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR "/src/SimpleInventory"
RUN dotnet build "SimpleInventory.csproj"

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]